version: 0.PRE.{build}
branches:
  only:
  - master
skip_tags: true
environment:
    matrix:
        - BOOTSTRAP: gauche32
        - BOOTSTRAP: sagittarius64
        - BOOTSTRAP: racket32
        - BOOTSTRAP: ironscheme64

install:
    - cinst ninja
    - set PATH=c:/tools/ninja;%PATH%

build_script:
    - cmd: cmake -DBOOTSTRAP=%BOOTSTRAP% -DSKIP_LONGRUN=ON -DSKIP_FFITESTS=ON -P %APPVEYOR_BUILD_FOLDER%/integration/buildhost-win/test-on-admin.cmake

cache:
    - c:/projects/yuni/work/pkgcache -> integration/buildhost-win/test-on-admin.cmake
