version: 0.PRE.{build}
branches:
  only:
  - master
skip_tags: true
environment:
    matrix:
        - BOOTSTRAP: gauche32
        - BOOTSTRAP: sagittarius32

install:
    - cinst ninja
    - set PATH=c:/tools/ninja;%PATH%

build_script:
    - cmd: cmake -DBOOTSTRAP=%BOOTSTRAP% -P %APPVEYOR_BUILD_FOLDER%/integration/buildhost-win/test-on-admin.cmake

